logging:
  config: classpath:log/logback-dev.xml

spring:
  datasource:
    hikari:
      master:
        jdbcUrl:
        username:
        password:
        driverClassName:
        #        maximumPoolSize: 5
        #        minimumIdle: 3
        poolName:
      slave:
        jdbcUrl:
        username:
        password:
        driverClassName:
        #        maximumPoolSize: 5
        #        minimumIdle: 3
        poolName:
  redis:
    master:
      host:
      port:
    slaves:
      - host:
        port:
    password:
    database:
  cache:
    type: redis
  batch:
    job:
      enabled: false
      names: ${job.name:NONE}

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  token:
    secretKey:
